site_name: Code California Playbook
repo_url: https://github.com/cagov/playbook/
site_url: https://codecagov-playbook.readthedocs.io/en/latest/
theme:
    name: readthedocs
extra_css:
- css/extra.css
plugins:
- search

nav:
- Home: '/docs/index.md'
- Why:
    - 'Why': '/docs/why/why.md'
- About:
    - 'About': '/docs/about/about.md'
