site_name: Code California Playbook
site_url: https://codecagov-playbook.readthedocs.io/en/latest/

repo_url: https://github.com/cagov/playbook/

theme:
    name: readthedocs

pages:
    - Welcome: README.md
    - Why: why.md
    - Policy: policy.md
    - About: about.md
    - Community: community.md
    - Events: events.md
    - Training: training.md
    - Platform: platform.md
    - Governance: governance.md
    - Onboarding: onboarding.md
    - Workflow: workflow.md
    - Licensing: licensing.md
    - Roadmap: roadmap.md
    - Metrics: metrics.md
    - Reporting: reporting.md
    - Outreach: outreach.md
    - Ops: ops.md
    - Code California: https://cagov.github.io/codeCAgov/

extra_css:
    - css/extra.css

plugins:
    - search
