site_name: Code California Playbook

repo_url: https://github.com/cagov/playbook/

site_url: https://codecagov-playbook.readthedocs.io/en/latest/

theme:
    name: readthedocs
      
extra_css:
- css/extra.css

plugins:
    - search

nav:
    - Intro: docs/readme.md
    - Why:
        - Why: docs/why/why.md
    - About:
        - About: docs/about/about.md

  social:
    - type: globe
      link: https://cagov.github.io/codeCAgov/
    - type: twitter
      link: https://twitter.com/codecagov
      
# Copyright
copyright: "Coded with heart by Code California"
