site_name: Code California Playbook
site_url: https://codecagov-playbook.readthedocs.io/en/latest/

repo_url: https://github.com/cagov/playbook/

theme:
    name: readthedocs

pages:
    - Welcome: README.md
    - Why: why.md
    - Policy: policy.md
    - Feedback: feedback.md
    - About: about.md
    - Community: community.md
    - Training: training.md
    - Events: events.md
    - Platform: platform.md
    - Governance: governance.md
    - Inventory: inventory.md
    - Onboarding: onboarding.md
    - Workflow: workflow.md
    - Licensing: licensing.md
    - Roadmap: roadmap.md
    - Metrics: metrics.md
    - Reporting: reporting.md
    - Outreach: outreach.md
    - Operations: operations.md

extra_css:
    - css/extra.css

plugins:
    - search

google_analytics: ['UA-129760497-3', 'playbook.code.ca.gov']
